<a href="https://colab.research.google.com/github/Ziroint/Desain-AnalisisAlgoritma/blob/main/DAA_Pertemuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

List

In [41]:
aList = ["Ziro", 18, "Kambing", True]
print("aList =", aList)

aList = ['Ziro', 18, 'Kambing', True]


Latihan

In [2]:
Mahasiswa = ["Yeru Dwi Pratama Halim",2021071033,"Informatika","Desain dan Analisis Algoritma", "14/09/2022" , "Universitas Pembangunan Jaya"]
print("Mahasiswa = ", Mahasiswa)

Mahasiswa =  ['Yeru Dwi Pratama Halim', 2021071033, 'Informatika', 'Desain dan Analisis Algoritma', '14/09/2022', 'Universitas Pembangunan Jaya']


Catatan

In [3]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
print("warna yang anda pilih adalah =" , bin_colors[1])

warna yang anda pilih adalah = Green


Latihan

In [4]:
print("NIM Mahasiswa = ", Mahasiswa[1])

NIM Mahasiswa =  2021071033


In [5]:
print("Nama Universitas = ", Mahasiswa[5])

Nama Universitas =  Universitas Pembangunan Jaya


Catatan

In [6]:
print("colors = ",bin_colors[0:2])

colors =  ['Red', 'Green']


Latihan

In [7]:
print("Nim dan Prodi = ",Mahasiswa[1:3])

Nim dan Prodi =  [2021071033, 'Informatika']


Catatan List

In [8]:
#bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for acolor in bin_colors:
  print(acolor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


Latihan

In [9]:
#Mahasiswa = ["Yeru Dwi Pratama Halim", 2021071033 ,"Informatika","Desain dan Analisis Algoritma", "14/09/2022" , "Universitas Pembangunan Jaya"]
for i in Mahasiswa:
  print("upj", i)
  #print(f"UPJ {i}")

upj Yeru Dwi Pratama Halim
upj 2021071033
upj Informatika
upj Desain dan Analisis Algoritma
upj 14/09/2022
upj Universitas Pembangunan Jaya


Catatan Tuple

In [10]:
bin_colors =('Red','Green','Blue','Yellow')
print(bin_colors[1])
print(bin_colors[2:])
print(bin_colors[:2])

Green
('Blue', 'Yellow')
('Red', 'Green')


Latihan

In [11]:
UPJ = ("Universitas","Pembangunan", "Jaya")
print(UPJ)

('Universitas', 'Pembangunan', 'Jaya')


In [12]:
nested_tuple = (100, (200,400,600), 300, (400,800))
print("Pertama = ", nested_tuple[0])
print("Kedua = ", nested_tuple[1])
print("Ketiga = ", nested_tuple[2])
print("Keempat = ", nested_tuple[3])

Pertama =  100
Kedua =  (200, 400, 600)
Ketiga =  300
Keempat =  (400, 800)


Catatan Dictionary

In [13]:
bin_colors ={
    "manual_color":"Yellow", 
    "approved_color":"Green", 
    "refused_color":"Red"}
print(bin_colors)
bin_colors["manual_color"] = "Blue"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}
{'manual_color': 'Blue', 'approved_color': 'Green', 'refused_color': 'Red'}


In [14]:
print(bin_colors.get('approved_color'))

print(bin_colors["approved_color"])

Green
Green


In [15]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Blue', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [16]:
Mahasiswa = {
    "Nama":"Yeru Dwi Pratama Halim",
    "NIM" : "2021071033",
    "Prodi" : "Informatika",
    "Universitas" : "UPJ"
}
print(Mahasiswa)

{'Nama': 'Yeru Dwi Pratama Halim', 'NIM': '2021071033', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


Catatan Set

In [17]:
green ={'grass','leaves'}
print(green)

{'leaves', 'grass'}


In [18]:
warna ={'red','blue','yellow','red','blue'}
print(warna)

{'blue', 'red', 'yellow'}


In [19]:
yellow = {'dandelious', 'leaves', 'fire hydrant'}
red = { 'fire hydrant', 'blood', 'rose', 'leaves'}
print(yellow|red)
print(yellow&red)

{'rose', 'fire hydrant', 'leaves', 'blood', 'dandelious'}
{'leaves', 'fire hydrant'}


import pandas (Data Frame)

In [20]:
import pandas as pd
df = pd.DataFrame([
    ['1','Fares',32,True],
    ['2','Elena',23,False],
    ['3','Steven',40,True]
])
print(df)

   0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True


In [21]:
df.columns = ['id','name','age','decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


In [22]:
#seleksi kolom
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [23]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [24]:
#Row Selection
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [25]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [26]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [27]:
mhs = pd.DataFrame([
    ['1','Informatika',50,30,20],
    ['2','Sistem Informasi', 55,30,25],
    ['3', 'Teknik Sipil', 40,30,10]
])
mhs.columns = ['No','Prodi','Mahasiswa','Lakilaki','Perempuan']
mhs[['No','Prodi','Mahasiswa','Lakilaki','Perempuan']]

No             Prodi  Mahasiswa  Lakilaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

Matriks

In [28]:
import numpy as np

In [29]:
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

print(type(myMatrix))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


Latihan Matix

In [35]:
myMatrix = np.array([[100,200,300],[700,600,500],[900,1000,800]])
print(myMatrix)
print("\nMatrix ketika ditranspose")
print(np.transpose(myMatrix))

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Matrix ketika ditranspose
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


Vector

In [31]:
myVector = [22,33,44,55]
print(myVector)
print(type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [32]:
myVector = np.array([22,33,44,55])
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [33]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self,item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-1]
  def size(self):
    return len(self.items)


In [34]:
stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

print(stack.pop())
print(stack.isEmpty())

Yellow
False


QUEUE

In [38]:
class Queue(object):
  def __init__(self):
    self.items =[]
  def isEmpty(self):
    return self.items==[]
  def enqueue(self,item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)


In [40]:
queue = Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())
print(queue.dequeue())
print(queue.dequeue())

4
Red
Green
